# Práctica Grupos 3

## Descripción

Una vez realizada la Práctica Grupos 2 y teniendo clara la pregunta que le queremos hacer a los datos tenemos que escoger un algoritmo de ML. Aún no conocemos demasiados, pero parece que un algoritmo de aprendizaje supervisado utilizando regresión linear puede ser suficiente.

Es decir, en esta práctica vamos a realizar una regresión lineal para estimar el precio de un diamante a partir de su atributo **carat**.

## Guion

In [2]:
import pandas as pd
df = pd.read_csv('diamonds_example.csv')

1) En primer lugar observamos y comprendemos los datos (Fase 1).

1.1)  Algunas funciones útiles para este fin:

- head()
- describe()
- dtypes
- shape
- select_dtypes(include=['object'])
- isnull()

Prueba cada una de ellas e inserta como comentario para qué sirven.

In [3]:
print(df.head()) # muestra los datos
print(df.describe()) # te muestra variables de contador, mediana, media, minimo, maximo....
print(df.dtypes) # muestra los tipos de datos (columnas)
print(df.shape) # indica la magnitud de los datos
print(df.select_dtypes(include='object')) # muestra solo los datos de tipo objectos
print(df.isnull()) # indica si los datos son de tipo null

categorical_feature_mask = df.dtypes==object
categorical_cols = df.columns[categorical_feature_mask].tolist()

df[categorical_cols]

   no  carat      cut color clarity  depth  table  price  x size  y size  \
0   1   0.23    Ideal     E     SI2   61.5   55.0    326    3.95    3.98
1   2   0.21  Premium     E     SI1   59.8   61.0    326    3.89    3.84
2   3   0.23     Good     E     VS1   56.9   65.0    327    4.05    4.07
3   4   0.29  Premium     I     VS2   62.4   58.0    334    4.20    4.23
4   5   0.31     Good     J     SI2   63.3   58.0    335    4.34    4.35

   z size
0    2.43
1    2.31
2    2.31
3    2.63
4    2.75
                 no         carat         depth         table         price  \
count  53940.000000  53940.000000  53940.000000  53940.000000  53940.000000
mean   26970.500000      0.797940     61.749405     57.457184   3932.799722
std    15571.281097      0.474011      1.432621      2.234491   3989.439738
min        1.000000      0.200000     43.000000     43.000000    326.000000
25%    13485.750000      0.400000     61.000000     56.000000    950.000000
50%    26970.500000      0.700000     61.800000     57.000000   2401.000000
75%    40455.250000      1.040000     62.500000     59.000000   5324.250000
max    53940.000000      5.010000     79.000000     95.000000  18823.000000

             x size        y size        z size
count  53940.000000  53940.000000  53940.000000
mean       5.731157      5.734526      3.538734
std        1.121761      1.142135      0.705699
min        0.000000      0.000000      0.000000
25%        4.710000      4.720000      2.910000
50%        5.700000      5.710000      3.530000
75%        6.540000      6.540000      4.040000
max       10.740000     58.900000     31.800000
no           int64
carat      float64
cut         object
color       object
clarity     object
depth      float64
table      float64
price        int64
x size     float64
y size     float64
z size     float64
dtype: object
(53940, 11)
             cut color clarity
0          Ideal     E     SI2
1        Premium     E     SI1
2           Good     E     VS1
3        Premium     I     VS2
4           Good     J     SI2
...          ...   ...     ...
53935      Ideal     D     SI1
53936       Good     D     SI1
53937  Very Good     D     SI1
53938    Premium     H     SI2
53939      Ideal     D     SI2

[53940 rows x 3 columns]
          no  carat    cut  color  clarity  depth  table  price  x size  \
0      False  False  False  False    False  False  False  False   False
1      False  False  False  False    False  False  False  False   False
2      False  False  False  False    False  False  False  False   False
3      False  False  False  False    False  False  False  False   False
4      False  False  False  False    False  False  False  False   False
...      ...    ...    ...    ...      ...    ...    ...    ...     ...
53935  False  False  False  False    False  False  False  False   False
53936  False  False  False  False    False  False  False  False   False
53937  False  False  False  False    False  False  False  False   False
53938  False  False  False  False    False  False  False  False   False
53939  False  False  False  False    False  False  False  False   False

       y size  z size
0       False   False
1       False   False
2       False   False
3       False   False
4       False   False
...       ...     ...
53935   False   False
53936   False   False
53937   False   False
53938   False   False
53939   False   False

[53940 rows x 11 columns]

             cut color clarity
0          Ideal     E     SI2
1        Premium     E     SI1
2           Good     E     VS1
3        Premium     I     VS2
4           Good     J     SI2
...          ...   ...     ...
53935      Ideal     D     SI1
53936       Good     D     SI1
53937  Very Good     D     SI1
53938    Premium     H     SI2
53939      Ideal     D     SI2

[53940 rows x 3 columns]

1.2) Existen otros enfoques más avanzados. Por ejemplo, crear máscaras con tipos de datos específicos

    categorical_feature_mask = df.dtypes==object
    categorical_cols = df.columns[categorical_feature_mask].tolist()
    
    df[categorical_cols]

2) Si repasas los comentarios de la lección 3.2 verás que hay datos categóricos, datos nulos y datos erróneos. Para simplificar la tarea, los datos cargados son totalmente correctos y solamente tendremos que tratar los datos nulos y categóricos.

2.1) Hay que comprobar si hay variables sesgadas, para ello utilizaremos la misma técnica que en la **Práctica 1 -> 5) y 6)**. Borra las variables que consideres adecuadas de acuerdo con el resultado obtenido.

In [4]:
df.count()

no         53940
carat      53940
cut        53940
color      53940
clarity    53940
depth      53940
table      53940
price      53940
x size     53940
y size     53940
z size     53940
dtype: int64

2.2) Al contrario de lo que muestra la presentación, tenemos 53840 filas. Por lo que en principio podemos borrar las filas que contienen algún valor nulo si es que los hubiese. Para ello, repasa la **Práctica 1 -> 7)**. 

¿Cuántas filas se han borrado?

In [5]:
df = df.dropna(how='any')
df.shape
df.head()

,no,carat,cut,color,clarity,depth,table,price,x size,y size,z size
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75

2.3) Existe una variable que debe ser borrada porque no aporta nada al modelo. ¿Puedes identificarla? Utiliza la siguiente expresión para elimnarla:

        df = df.drop(columns=['NOMBRE_DE_VARIABLE'],axis=1)

In [6]:
df = df.drop(columns=['no'],axis=1)
df.head()

   carat      cut color clarity  depth  table  price  x size  y size  z size
0   0.23    Ideal     E     SI2   61.5   55.0    326    3.95    3.98    2.43
1   0.21  Premium     E     SI1   59.8   61.0    326    3.89    3.84    2.31
2   0.23     Good     E     VS1   56.9   65.0    327    4.05    4.07    2.31
3   0.29  Premium     I     VS2   62.4   58.0    334    4.20    4.23    2.63
4   0.31     Good     J     SI2   63.3   58.0    335    4.34    4.35    2.75

**EXTRA** partir de ahora vamos a emplear la librería de ML de Python *scikit-learn*. ¿Puedes describir sus principales características?

Es un una libreria con herramientas eficientes para la prediccion de datos y analisis de los mismos. 

Cuenta con algoritmos de:

- Clasidicacion
- Regresion
- Clustering
- Dimensionalidad

Compatible y de hecho esta creado en base de numpy, scipy y matplotlib.

2.3) Ahora hay que transformar los datos categóricos. Si recordáis, existen dos técnicas principales, one-hot encoding y label encoding. Label encoding solo es válido para variables que denotan notas o valoraciones, one-hot encoding para todos los casos.

Para homogeneizar los resultados, vamos a utilizar label encoding con *cut* y one-hot encoding con *color* y *clarity*.

A continuación, completa las líneas comentadas con TODO con tu propio código:

In [7]:
from sklearn import preprocessing

# Cargamos el label encoder
label_encoder = preprocessing.LabelEncoder()

# Lo aplicamos sobre la la columna 'cut' -> le.fit_transform()
#TODO
df['cut']= label_encoder.fit_transform(df['cut']) 

# Ahora vamos a transformar la variable 'color'
df['color']= label_encoder.fit_transform(df['color']) 

# Cargamos el one-hot encoder
hot_encoder=preprocessing.OneHotEncoder(sparse=False)

# ¿Qué significa el atributo sparse? Proporciona la respuesta por medio de un comentario
# TODO Hacer una matriz dispersa. Clasificar las temáticas de los datos que se reunen.

# Para simplificar el proceso, vamos a realizar las operaciones en un nuevo DataFrame formado por los datos a modificar
# Aplicamos el encoder la columna 'color' -> hot_encoder.fit_transform()
#TODO
datos_color = hot_encoder.fit_transform(df[['color']]) 
# Para obtener un nuevo DataFrame ->  pd.DataFrame (resultado_anterior)
#TODO color_data = 
color_data = pd.DataFrame(datos_color)

# Para que los nombres de las nuevas columnas tengan sentido, utilizaremos al siguiente función
#TODO color_data.columns = hot_encoder.get_feature_names(['NOMBRE_DE_VARIABLE'])
color_data.columns = hot_encoder.get_feature_names(['color'])
# Eliminamos la variable color de nuestro dataset original
#TODO
df.drop(columns=["color"], axis = 1)

#Y le añadimos el nuevo DataFrame con el comando concat de Pandas
#TODO
df = pd.concat([df, color_data], axis = 1)

#Observa que el DataFrame original ha cambiado
print(df.head())
print("-----------------------------------------------------------------")
# Haz lo mismo con la variable 'clarity'
#TODO
datos_clarity = hot_encoder.fit_transform(df[['clarity']]) 
clarity_data = pd.DataFrame(datos_clarity)
clarity_data.columns = hot_encoder.get_feature_names(['clarity'])
df.drop(columns=["clarity"], axis = 1)
df = pd.concat([df, clarity_data], axis = 1)
print(df.head())

   carat  cut  color clarity  depth  table  price  x size  y size  z size  \
0   0.23    2      1     SI2   61.5   55.0    326    3.95    3.98    2.43
1   0.21    3      1     SI1   59.8   61.0    326    3.89    3.84    2.31
2   0.23    1      1     VS1   56.9   65.0    327    4.05    4.07    2.31
3   0.29    3      5     VS2   62.4   58.0    334    4.20    4.23    2.63
4   0.31    1      6     SI2   63.3   58.0    335    4.34    4.35    2.75

   color_0  color_1  color_2  color_3  color_4  color_5  color_6
0      0.0      1.0      0.0      0.0      0.0      0.0      0.0
1      0.0      1.0      0.0      0.0      0.0      0.0      0.0
2      0.0      1.0      0.0      0.0      0.0      0.0      0.0
3      0.0      0.0      0.0      0.0      0.0      1.0      0.0
4      0.0      0.0      0.0      0.0      0.0      0.0      1.0
-----------------------------------------------------------------
   carat  cut  color clarity  depth  table  price  x size  y size  z size  \
0   0.23    2      1     SI2   61.5   55.0    326    3.95    3.98    2.43
1   0.21    3      1     SI1   59.8   61.0    326    3.89    3.84    2.31
2   0.23    1      1     VS1   56.9   65.0    327    4.05    4.07    2.31
3   0.29    3      5     VS2   62.4   58.0    334    4.20    4.23    2.63
4   0.31    1      6     SI2   63.3   58.0    335    4.34    4.35    2.75

   ...  color_5  color_6  clarity_I1  clarity_IF  clarity_SI1  clarity_SI2  \
0  ...      0.0      0.0         0.0         0.0          0.0          1.0
1  ...      0.0      0.0         0.0         0.0          1.0          0.0
2  ...      0.0      0.0         0.0         0.0          0.0          0.0
3  ...      1.0      0.0         0.0         0.0          0.0          0.0
4  ...      0.0      1.0         0.0         0.0          0.0          1.0

   clarity_VS1  clarity_VS2  clarity_VVS1  clarity_VVS2
0          0.0          0.0           0.0           0.0
1          0.0          0.0           0.0           0.0
2          1.0          0.0           0.0           0.0
3          0.0          1.0           0.0           0.0
4          0.0          0.0           0.0           0.0

[5 rows x 25 columns]

3) Ahora que tenemos los datos listos, podemos construir el modelo de ML utilizando regresión lineal y entrenarlo. Es decir, comenzamos la fase 3. 

Al igual que en el punto anterior, completa las líneas comentadas con TODO con tu propio código:

In [12]:
from sklearn.model_selection import train_test_split

# Tal y como realizamos en la práctica 1, Dividimos los datos que tenemos en datos de entrenamiento 
# o training set (conjunto de datos iniciales utilizados por el modelo para entender el problema y aprender sobre él) 
# y datos de prueba o test set (conjunto de datos utilizados para comprobar lo que ha aprendido 
# el modelo después de haber sido entrenado). 
# Normalmente se utiliza un 80% de los datos para entrenamiento y un 20% para tests.


# Selecciona la variable X (Si tienes dudas, consulta la Práctica 1)
#TODO 
X = df['x size']


# Selecciona la variable y (Si tienes dudas, consulta la Práctica 1)
#TODO 
y = df['y size']

# print(X)
# print(y)

# Obten X_train, X_test, y_train, y_test con un tamaño de entrenamiento del 80% (Si tienes dudas, consulta la Práctica 1)
#TODO 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.80)

from sklearn import linear_model
# Inicializamos el modelo de regresión lineal
regression = linear_model.LinearRegression()


# Creamos las variables de Python regression_train_x y regression_train_y a partir de los valores de X_train e y_train
regression_train_x = X_train.values
regression_train_y = y_train.values

# Entrenamos el modelo
regression = regression.fit(regression_train_x.reshape(-1, 1), regression_train_y.reshape(-1, 1))

# Es importante que ambas variables tengan dos dimensiones: una para los valores a entrenar y otra para otras variables.
# Nosotros solo usamos uan variable, pero la función fit espera una array de dos dimensiones
# Por eso hemos empleado la función reshape

0        3.95
1        3.89
2        4.05
3        4.20
4        4.34
         ...
53935    5.75
53936    5.69
53937    5.66
53938    6.15
53939    5.83
Name: x size, Length: 53940, dtype: float64
0        3.98
1        3.84
2        4.07
3        4.23
4        4.35
         ...
53935    5.76
53936    5.75
53937    5.68
53938    6.12
53939    5.87
Name: y size, Length: 53940, dtype: float64
LinearRegression()

4) Llegamos a la fase 4. ¿Será bueno nuestro modelo? 

Vamos a emplear diversas estadísticas y a visualizar los resultados

Al igual que en los punto anteriores, completa las líneas comentadas con TODO con tu propio código:

In [14]:
from sklearn import metrics
import matplotlib.pyplot as plt

# Replica los pasos anteriores para crear regression_test_x  y regression_test_y
#TODO
regression_test_x = X_test.values
regression_test_y = y_test.values

# En lugar de utilizar la función fit, vamos a utilizar la función predict. No olvides hacer el reshape.
#TODO
regression = regression.predict(regression_test_x.reshape(-1, 1), regression_test_y.reshape(-1, 1))
# Ahora imprimiremos los coeficientes de la regresión, la media de los mínimos cuadrados y el R^2 
#TODO imprime y explica qué significan cada uno de ellos


# Vamos a mostrar el resultado en una gráfica
plt.scatter(regression_test_x, regression_test_y,  color='black')
plt.plot(regression_test_x, prediction_y, color='red', linewidth=3)
plt.show()

# TODO ¿Cómo interpretas los datos de la misma?

TypeError: predict() takes 2 positional arguments but 3 were given

5) Hemos obetenido una precisión del 85%. Mejora estos resultados como parte del paso 5.

In [ ]:
#TODO